# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CMD-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'  # 使用与 RStudio 相同的版本
      - name: Install Pandoc
        run: |
          brew install pandoc  # 使用 Homebrew 安装 Pandoc
      - name: Install required packages
        run: |
          Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org/')"
          Rscript -e "install.packages('ggplot2', repos='https://cloud.r-project.org/')"
          Rscript -e "install.packages('rcmdcheck', repos='https://cloud.r-project.org/')"
      - name: Check all packages
        run: |
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
        shell: bash
